export const latexCommands = [
  { command: "\\alpha", description: "Greek letter alpha" },
  { command: "\\beta", description: "Greek letter beta" },
  { command: "\\gamma", description: "Greek letter gamma" },
  { command: "\\delta", description: "Greek letter delta" },
  { command: "\\epsilon", description: "Greek letter epsilon" },
  { command: "\\zeta", description: "Greek letter zeta" },
  { command: "\\eta", description: "Greek letter eta" },
  { command: "\\theta", description: "Greek letter theta" },
  { command: "\\iota", description: "Greek letter iota" },
  { command: "\\kappa", description: "Greek letter kappa" },
  { command: "\\lambda", description: "Greek letter lambda" },
  { command: "\\mu", description: "Greek letter mu" },
  { command: "\\nu", description: "Greek letter nu" },
  { command: "\\xi", description: "Greek letter xi" },
  { command: "\\pi", description: "Greek letter pi" },
  { command: "\\rho", description: "Greek letter rho" },
  { command: "\\sigma", description: "Greek letter sigma" },
  { command: "\\tau", description: "Greek letter tau" },
  { command: "\\upsilon", description: "Greek letter upsilon" },
  { command: "\\phi", description: "Greek letter phi" },
  { command: "\\chi", description: "Greek letter chi" },
  { command: "\\psi", description: "Greek letter psi" },
  { command: "\\omega", description: "Greek letter omega" },
  { command: "\\sum", description: "Summation" },
  { command: "\\prod", description: "Product" },
  { command: "\\int", description: "Integral" },
  { command: "\\frac", description: "Fraction" },
  { command: "\\sqrt", description: "Square root" },
  { command: "\\lim", description: "Limit" },
];
